# Generated by Django 4.0.4 on 2022-05-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название (ед.ч)')),
                ('name_plural', models.CharField(max_length=50, verbose_name='Название (мн.ч)')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип кабеля',
                'verbose_name_plural': 'Типы кабелей',
                'ordering': ('pk',),
            },
        ),
    ]
