# Generated by Django 4.0.4 on 2022-05-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabletype',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/cable_types/', verbose_name='Фото'),
        ),
    ]
