# Generated by Django 4.0.4 on 2022-05-25 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cabletype_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('length_m', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Длина, м.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('units_in_stock', models.PositiveSmallIntegerField(verbose_name='Количество в наличии')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.cabletype')),
            ],
            options={
                'verbose_name': 'Кабель',
                'verbose_name_plural': 'Кабели',
                'ordering': ('type', 'price'),
            },
        ),
    ]
