# Generated by Django 4.0.4 on 2022-06-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cable_is_for_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_last_update_date',
        ),
    ]
