# Generated by Django 4.0.4 on 2022-05-26 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cable',
            options={'ordering': ('type', 'price'), 'verbose_name': 'кабель', 'verbose_name_plural': 'кабели'},
        ),
        migrations.AlterModelOptions(
            name='cabletype',
            options={'ordering': ('pk',), 'verbose_name': 'тип кабеля', 'verbose_name_plural': 'типы кабелей'},
        ),
        migrations.AlterField(
            model_name='cable',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='length_m',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='длина, м.'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='name',
            field=models.CharField(max_length=50, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='units_in_stock',
            field=models.PositiveSmallIntegerField(verbose_name='количество в наличии'),
        ),
        migrations.AlterField(
            model_name='cabletype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='cabletype',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='название (ед.ч)'),
        ),
        migrations.AlterField(
            model_name='cabletype',
            name='name_plural',
            field=models.CharField(max_length=50, verbose_name='название (мн.ч)'),
        ),
        migrations.AlterField(
            model_name='cabletype',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/cable_types/', verbose_name='фото'),
        ),
        migrations.CreateModel(
            name='CablePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/cable_photos/%Y/%m', verbose_name='фото')),
                ('is_title', models.BooleanField(verbose_name='является титульным')),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cable')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фотографии',
                'ordering': ('pk', '-is_title'),
            },
        ),
    ]
