# Generated by Django 4.0.4 on 2022-05-26 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_cable_options_alter_cabletype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cable',
            name='length_m',
        ),
        migrations.AddField(
            model_name='cable',
            name='length_sm',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='длина, см.'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='цена, руб.'),
        ),
        migrations.AlterField(
            model_name='cablephoto',
            name='cable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cable', verbose_name='кабель'),
        ),
        migrations.AlterField(
            model_name='cabletype',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/cable_types/', verbose_name='фото'),
        ),
    ]
