# Generated by Django 4.0.4 on 2022-05-28 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_remove_order_customer_remove_ordereditem_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='имя')),
                ('last_name', models.CharField(max_length=15, verbose_name='фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='отчество')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='gользователь')),
            ],
        ),
    ]
