# Generated by Django 4.0.4 on 2022-05-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_alter_customer_options_alter_customer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='quantity',
            field=models.IntegerField(verbose_name='количество'),
        ),
    ]
