# Generated by Django 4.0.4 on 2022-05-29 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_orderedproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='время добавления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='quantity',
            field=models.SmallIntegerField(default=0, verbose_name='количество'),
        ),
    ]
