# Generated by Django 4.0.4 on 2022-05-30 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_orderedproduct_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='title',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(default='', max_length=70, null=True, verbose_name='область'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.customer', verbose_name='покупатель'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='почтовый индекс'),
        ),
    ]
