# Generated by Django 4.0.4 on 2022-05-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_shippingaddress_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='адрес'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='', max_length=50, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='', max_length=70, verbose_name='область'),
        ),
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(default='', max_length=10, verbose_name='почтовый индекс'),
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
