# Generated by Django 4.0.4 on 2022-05-31 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_customer_address_remove_customer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='shop.customer', verbose_name='покупатель'),
        ),
    ]
