# Generated by Django 4.0.4 on 2022-06-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_shippingaddress_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_cart', 'In Cart'), ('accepted', 'Accepted'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('complete', 'Complete')], default='in_cart', max_length=10, verbose_name='статус заказа'),
        ),
    ]
