# Generated by Django 4.0.4 on 2022-06-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'адрес доставки', 'verbose_name_plural': 'адреса доставки'},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата оформления заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В корзине', 'In Cart'), ('Принят', 'Accepted'), ('На сборе', 'Preparing'), ('Отправлен', 'Shipped'), ('Выполнен', 'Complete')], default='В корзине', max_length=10, verbose_name='статус заказа'),
        ),
    ]
