# Generated by Django 4.0.4 on 2022-06-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_shippingaddress_options_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IC', 'В корзине'), ('AC', 'Принят'), ('PR', 'На сборе'), ('SH', 'Отправлен'), ('CO', 'Выполнен')], default='IC', max_length=2, verbose_name='статус заказа'),
        ),
    ]
