# Generated by Django 4.0.4 on 2022-06-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В корзине', 'In Cart'), ('Принят', 'Accepted'), ('На сборе', 'Preparing'), ('Отправлен', 'Shipped'), ('Выполнен', 'Complete')], default='В корзине', max_length=10, verbose_name='статус заказа'),
        ),
    ]
