# Generated by Django 4.0.4 on 2022-06-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IC', 'В корзине'), ('AC', 'Принят'), ('PR', 'На сборе'), ('SH', 'Отправлен'), ('CO', 'Выполнен')], default='IC', max_length=10, null=True, verbose_name='статус заказа'),
        ),
    ]
