# Generated by Django 4.0.4 on 2022-06-01 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_order_is_active_remove_order_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата оформления заказа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IC', 'В корзине'), ('AC', 'Принят'), ('PR', 'На сборе'), ('SH', 'Отправлен'), ('CO', 'Выполнен')], default='IC', max_length=10, verbose_name='статус заказа'),
        ),
    ]
