# Generated by Django 4.0.4 on 2022-06-01 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_order_order_date_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AddField(
            model_name='order',
            name='order_accepted_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата оформления заказа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_last_update_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата последнего обновления заказа'),
            preserve_default=False,
        ),
    ]
