# Generated by Django 4.0.4 on 2022-06-02 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_order_order_date_order_order_accepted_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shippingaddress', verbose_name='адресс доставки'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='основной адрес'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='shop.customer', verbose_name='покупатель'),
        ),
    ]
