# Generated by Django 4.0.4 on 2022-06-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_order_shipping_address_shippingaddress_is_primary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='is_primary',
        ),
    ]
