# Generated by Django 4.0.4 on 2022-06-06 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_remove_shippingaddress_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('PU', 'Самовывоз'), ('DE', 'Доставка ТК')], default='DE', max_length=10, verbose_name='способ получения'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='quantity',
            field=models.SmallIntegerField(default=0, verbose_name='заказанное количество'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer', verbose_name='покупатель'),
        ),
    ]
